version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd webapp && npm install
  build:
    commands:
      # CWD is $repo/webapp
      - echo "Build started by $CODEBUILD_INITIATOR"
      # TODO we may eventually want logic here to allow different environment
      # targets to point at either the mock API or the live API
      - npm run build-ci --c standalone
  post_build:
    commands:
      # CWD is $repo/webapp
      - codebuild/deploy.sh

artifacts:
  files:
    - '**/*'
  base-directory: webapp/dist/sb-digital-library
  name: sb-digital-library-webapp-$(git describe --always --dirty).zip

cache:
  paths:
    - 'webapp/node_modules'
